Use S6
Go

-- Rau
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRAN
		SELECT * FROM Echipe
		WAITFOR DELAY '00:00:10'
		SELECT * FROM Echipe
		COMMIT TRAN

-- Rezolvat
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
	BEGIN TRAN
		SELECT * FROM Echipe
		WAITFOR DELAY '00:00:10'
		SELECT * FROM Echipe
		COMMIT TRAN